# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  # Salt Master Server
  config.vm.define "saltmaster" do |saltmaster|
    saltmaster.vm.box = "generic/ubuntu1804"
    saltmaster.vm.hostname = "saltmaster.jmlabs.net"
    saltmaster.vm.network "public_network", ip: "192.168.1.160"
    saltmaster.vm.provider "virtualbox" do |v|
      v.name = "saltmaster"
      v.memory = 2048
      v.cpus = 2
      # Prevent VirtualBox from interfering with host audio stack
      v.customize ["modifyvm", :id, "--audio", "none"]
    end
    saltmaster.vm.provision "shell", path: "bootstrap_saltmaster.sh"
  end

  NodeCount = 1

  # Salt Minion Nodes
  (1..NodeCount).each do |i|
    config.vm.define "saltminion#{i}" do |saltminion|
      saltminion.vm.box = "generic/ubuntu1804"
      saltminion.vm.hostname = "saltminion#{i}.jmlabs.net"
      saltminion.vm.network "public_network", ip: "192.168.1.16#{i}"
      saltminion.vm.provider "virtualbox" do |v|
        v.name = "saltminion#{i}"
        v.memory = 1024
        v.cpus = 1
        # Prevent VirtualBox from interfering with host audio stack
        v.customize ["modifyvm", :id, "--audio", "none"]
      end
      saltminion.vm.provision "shell", path: "bootstrap_saltminion.sh"
    end
  end

end
